### ISSUE TITLE
[BUG] {Missing 'total_num_of_captured_images'}

### ISSUE THREAD

**Issue by sabrinalokman** [luxonis/depthai#1148]
**Describe the bug**
I'm running a calibration routine using calibrate.py script to calibrate 3 modular camera with Oak FFC 4P PoE. Previously, I can calibrate it but with latest release, I got that error.

**Attach system log**
```
Cam: rgb and focus: True
Cam: left and focus: False
Cam: right and focus: False
Saving dataset to: dataset
Sensor name for rgb is IMX378
Sensor name for left is OV9282
Sensor name for right is OV9282
Starting image capture. Press the [ESC] key to abort.
Will take 26 total images.
Start capturing...
new minimum: {'ts': 0.30266400000000004, 'indicies': {'rgb': 0, 'left': 0, 'right': 0}} min required: 0.2
new minimum: {'ts': 0.09997200000000106, 'indicies': {'rgb': 1, 'left': 0, 'right': 0}} min required: 0.2
new minimum: {'ts': 0.003379999999996386, 'indicies': {'rgb': 2, 'left': 1, 'right': 1}} min required: 0.2
Time stamp of rgb is 0:14:08.653504
Markers count ... 44
Total markers needed -> 17
Traceback (most recent call last):
  File "calibrate.py", line 1181, in <module>
    Main().run()
  File "calibrate.py", line 1172, in run
    self.capture_images_sync()
  File "calibrate.py", line 914, in capture_images_sync
    tried[name] = self.parse_frame(frameMsg.getCvFrame(), name)
  File "calibrate.py", line 587, in parse_frame
    filename = calibUtils.image_filename(self.current_polygon, self.images_captured)
TypeError: image_filename() missing 1 required positional argument: 'total_num_of_captured_images'
```

**Comment by jakaskerl** [comment]
`git pull --recurse-submodules` should fix the issue.
