### ISSUE TITLE
error verbose option in demo app

### ISSUE THREAD

**Issue by abhatikar** [luxonis/depthai#228]
Traceback (most recent call last):
  File "depthai_demo.py", line 447, in <module>
    dai.startLoop()
  File "depthai_demo.py", line 279, in startLoop
    if args['verbose']: print_packet_info(nnet_packet)
  File "depthai_demo.py", line 208, in print_packet_info
    print("[{:.6f} {:15s}]".format(time()-time_start, packet.stream_name), end='')
AttributeError: 'depthai.NNetPacket' object has no attribute 'stream_name'

**Comment by alex-luxonis** [comment]
Thanks for the issue report! Should be fixed in PR https://github.com/luxonis/depthai/pull/229
