### ISSUE TITLE
[BUG] {Title of the bug}

### ISSUE THREAD

**Issue by AnamikaPaul** [luxonis/depthai#638]
**Describe the bug**
When I am trying to run the gen2-age-gender in my jetson nano, finding following error message below.

anamika@anamika-desktop:~/Downloads/venv/depthai-python/depthai-experiments/gen2-age-gender$ python3 main.py -cam
Starting pipeline...
Creating pipeline...
Creating Color Camera...
Traceback (most recent call last):
  File "main.py", line 142, in <module>
    device.startPipeline(create_pipeline())
  File "main.py", line 40, in create_pipeline
    stereo.setDefaultProfilePreset(dai.node.StereoDepth.PresetMode.HIGH_DENSITY)
**AttributeError: 'depthai.node.StereoDepth' object has no attribute 'setDefaultProfilePreset'**

**Comment by Erol444** [comment]
Hello @AnamikaPaul , could you try updating your depthai library version? `python3 -mpip install depthai -U`
Thanks, Erik
