### ISSUE TITLE
[BUG] Crash with corrupted double-linked list

### ISSUE THREAD

**Issue by geaxgx** [luxonis/depthai#724]
Hi,
Recently, I get crashes with stack trace printed on the console when working on my recent repo: https://github.com/geaxgx/depthai_handface . It is not systematic and seems to me that the crashes occur randomly.
I am currently using depthai 2.16.0 but also got the crashes with 2.15.4.
```
(g2) gx(0) [/home/gx/g2/depthai_handface]                                                                                 
-> ./demo.py -n 1  -p -a                                                                                                  
Palm detection blob     : /home/gx/g2/depthai_handface/models/palm_detection_pp_top2_th50_sh4.blob                        
Landmark blob           : /home/gx/g2/depthai_handface/models/hand_landmark_lite_sh4.blob                                 
Face detection blob     : /home/gx/g2/depthai_handface/models/face_detection_short_range_pp_top1_th50_sh1.blob            
Face landmark blob      : /home/gx/g2/depthai_handface/models/face_landmark_with_attention_pp_sh4.blob                    
Sensor resolution: (1920, 1080)                                                                                           
Internal camera FPS set to: 11                                                                                            
Internal camera image size: 1152 x 648 - pad_h: 252                                                                       
Creating pipeline...                                                                                                 
Creating Color Camera                                                                                                     
Creating Palm Detection pre processing image manip                                                                        
Creating Palm Detection Neural Network...                                                                                 
Creating Hand Landmark pre processing image manip                                                                         
Creating Hand Landmark Neural Network                                                                                     
Creating Face Detection pre processing image manip                                                                        
Creating Face Detection Neural Network                                                                                    
Creating Face Landmark pre processing image manip                                                                         
Creating Face Landmark Neural Network                                                                                     
Pipeline created.                                                                                                         
[14442C102162AACE00] [1.3] [47901.876] [NeuralNetwork(13)] [warning] Network compiled for 4 shaves, maximum available 13, 
compiling for 6 shaves likely will yield in better performance                                                            
[14442C102162AACE00] [1.3] [47901.879] [NeuralNetwork(5)] [warning] Network compiled for 4 shaves, maximum available 13, c
ompiling for 6 shaves likely will yield in better performance                                                             
[14442C102162AACE00] [1.3] [47901.880] [NeuralNetwork(8)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[14442C102162AACE00] [1.3] [47901.881] [NeuralNetwork(10)] [warning] Network compiled for 1 shaves, maximum available 13,
compiling for 6 shaves likely will yield in better performance
[14442C102162AACE00] [1.3] [47901.910] [NeuralNetwork(5)] [warning] The issued warnings are orientative, based on optimal
settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Pipeline started - USB speed: SUPER
[14442C102162AACE00] [1.3] [47901.910] [NeuralNetwork(8)] [warning] The issued warnings are orientative, based on optimal
settings for a single network, if multiple networks are running in parallel the optimal settings may vary
[14442C102162AACE00] [1.3] [47901.910] [NeuralNetwork(10)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
[14442C102162AACE00] [1.3] [47901.910] [NeuralNetwork(13)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Traceback (most recent call last):
  File "./demo.py", line 50, in <module>
    frame, faces, hands = tracker.next_frame()
  File "/home/gx/g2/depthai_handface/HandFaceTracker.py", line 817, in next_frame
    face = self.extract_face_data(res_lm_script, res_lm_nn)
  File "/home/gx/g2/depthai_handface/HandFaceTracker.py", line 645, in extract_face_data
    lm_score = res_lm_nn.getLayerFp16("lm_conv_faceflag")[0]
AttributeError: 'depthai.ADatatype' object has no attribute 'getLayerFp16'
corrupted double-linked list
Stack trace (most recent call last):
#21   Object "python3", at 0x563ac7722fef, in
#20   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f87abb98c86, in __libc_start_main
#19   Object "python3", at 0x563ac777e77b, in _Py_UnixMain
#18   Object "python3", at 0x563ac777e452, in
#17   Object "python3", at 0x563ac776b7e6, in Py_FinalizeEx
#16   Object "python3", at 0x563ac76efd24, in PyImport_Cleanup
#15   Object "python3", at 0x563ac76a9df1, in PyDict_SetItem
#14   Object "python3", at 0x563ac76d18d0, in
#13   Object "python3", at 0x563ac7653f7b, in
#12   Object "python3", at 0x563ac76e94ef, in
#11   Object "python3", at 0x563ac7653ee7, in
#10   Object "python3", at 0x563ac76e94ef, in
#9    Object "python3", at 0x563ac7653fd7, in
#8    Object "/home/gx/anaconda3/envs/g2/lib/python3.7/site-packages/depthai.cpython-37m-x86_64-linux-gnu.so", at 0x7f878d
263613, in
#7    Object "/home/gx/anaconda3/envs/g2/lib/python3.7/site-packages/depthai.cpython-37m-x86_64-linux-gnu.so", at 0x7f878d
284a66, in
#6    Object "/home/gx/anaconda3/envs/g2/lib/python3.7/site-packages/depthai.cpython-37m-x86_64-linux-gnu.so", at 0x7f878d
476548, in dai::Device::~Device()
#5    Object "/home/gx/anaconda3/envs/g2/lib/python3.7/site-packages/depthai.cpython-37m-x86_64-linux-gnu.so", at 0x7f878d
4762d0, in dai::Device::~Device()
#4    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f87abc0f13e, in cfree
#3    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f87abc078b9, in
#2    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f87abc00836, in
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f87abbb77f0, in abort
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f87abbb5e87, in gsignal
Abandon (signal envoyé par tkill() 19563 1000)
Abandon (core dumped)
(g2) gx(0) [/home/gx/g2/depthai_handface]
```     
[log_system_information.txt](https://github.com/luxonis/depthai/files/8955591/log_system_information.txt)

**Comment by geaxgx** [comment]
Another crash, with the same command as above, but with a different stack trace (after running about 1mn):

```
-> ./demo.py -n 1  -p -a
Palm detection blob     : /home/gx/g2/depthai_handface/models/palm_detection_pp_top2_th50_sh4.blob
Landmark blob           : /home/gx/g2/depthai_handface/models/hand_landmark_lite_sh4.blob
Face detection blob     : /home/gx/g2/depthai_handface/models/face_detection_short_range_pp_top1_th50_sh1.blob
Face landmark blob      : /home/gx/g2/depthai_handface/models/face_landmark_with_attention_pp_sh4.blob
Sensor resolution: (1920, 1080)
Internal camera FPS set to: 11
Internal camera image size: 1152 x 648 - pad_h: 252
Creating pipeline...
Creating Color Camera
Creating Palm Detection pre processing image manip
Creating Palm Detection Neural Network...
Creating Hand Landmark pre processing image manip
Creating Hand Landmark Neural Network
Creating Face Detection pre processing image manip
Creating Face Detection Neural Network
Creating Face Landmark pre processing image manip
Creating Face Landmark Neural Network
Pipeline created.
[14442C102162AACE00] [1.3] [2374.903] [NeuralNetwork(13)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[14442C102162AACE00] [1.3] [2374.906] [NeuralNetwork(5)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[14442C102162AACE00] [1.3] [2374.907] [NeuralNetwork(8)] [warning] Network compiled for 4 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[14442C102162AACE00] [1.3] [2374.908] [NeuralNetwork(10)] [warning] Network compiled for 1 shaves, maximum available 13, compiling for 6 shaves likely will yield in better performance
[14442C102162AACE00] [1.3] [2374.937] [NeuralNetwork(13)] [warning] The issued warnings are orientative, based on optimal
settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Pipeline started - USB speed: SUPER
[14442C102162AACE00] [1.3] [2374.937] [NeuralNetwork(5)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
[14442C102162AACE00] [1.3] [2374.937] [NeuralNetwork(8)] [warning] The issued warnings are orientative, based on optimal settings for a single network, if multiple networks are running in parallel the optimal settings may vary
[14442C102162AACE00] [1.3] [2374.937] [NeuralNetwork(10)] [warning] The issued warnings are orientative, based on optimal
settings for a single network, if multiple networks are running in parallel the optimal settings may vary
Stack trace (most recent call last):
#16   Object "python3", at 0x55a968e15fef, in
#15   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fc852513c86, in __libc_start_main
#14   Object "python3", at 0x55a968e7177b, in _Py_UnixMain
#13   Object "python3", at 0x55a968e71654, in
#12   Object "python3", at 0x55a968e70522, in PyRun_SimpleFileExFlags
#11   Object "python3", at 0x55a968e70330, in PyRun_FileExFlags
#10   Object "python3", at 0x55a968e65f13, in
#9    Object "python3", at 0x55a968d4e73b, in PyEval_EvalCode
#8    Object "python3", at 0x55a968d4e713, in PyEval_EvalCodeEx
#7    Object "python3", at 0x55a968d4d828, in _PyEval_EvalCodeWithName
#6    Object "python3", at 0x55a968e0673f, in _PyEval_EvalFrameDefault
#5    Object "python3", at 0x55a968d9de7a, in _PyFunction_FastCallKeywords
#4    Object "python3", at 0x55a968e0b39d, in _PyEval_EvalFrameDefault
#3    Object "python3", at 0x55a968d9ea30, in _PyCFunction_FastCallKeywords
#2    Object "python3", at 0x55a968d9e913, in _PyMethodDef_RawFastCallKeywords
#1    Object "/home/gx/anaconda3/envs/g2/lib/python3.7/site-packages/depthai.cpython-37m-x86_64-linux-gnu.so", at 0x7fc833bdf91b, in
#0    Object "/home/gx/anaconda3/envs/g2/lib/python3.7/site-packages/depthai.cpython-37m-x86_64-linux-gnu.so", at 0x7fc833ca7a60, in
Erreur de segmentation (Signal envoyé par le noyau [(nil)])
Erreur de segmentation (core dumped)
(g2) gx(0) [/home/gx/g2/depthai_handface]

```

**Comment by geaxgx** [comment]
To get more information, I let the program run in the background and note when it crahses. I reproduced the exact same  stack (from the second message) twice more. When it happens, it happens quickly (45s for the quickest). The problem also happens with a simpler pipeline by running:` ./demo.py -n 0`. In that case, only facemesh is used and there is no hand tracking.
Sometimes the program runs for more than half an hour without crash but block on a get()  of a depthai output queue, which potentially means there is also a problem in my code.

**Comment by geaxgx** [comment]
During my tests, I got one more stack trace idnetical to the first one (corrupted double-linked list). On another test, I got also a new error message, after running for 20 minutes
```
Traceback (most recent call last):
  File "./demo.py", line 50, in <module>
	frame, faces, hands = tracker.next_frame()
  File "/home/gx/g2/depthai_handface/HandFaceTracker.py", line 809, in next_frame
	res_lm_script = marshal.loads(self.q_face_manager_out.get().getData())
RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'face_manager_out' (X_LINK_ERROR)'
```
If I had to summarize in one word: unstable :-))

From now, trying on another camera (an OAK-D). The camera used previously is a an OAK-D (first version, T-shape, no shield).

**Comment by geaxgx** [comment]
I could reproduce the crash only once on the OAKD lite (2nd stack trace type), but otherwise the program could run for hours without problem. Could a faulty usb cable generate such errors ? Thoughts ?

From now, trying with another usb cable.

**Comment by geaxgx** [comment]
I couldn't reproduce the crash with another usb cable. So the problem was certainly this faulty cable.

And yes @szabi-luxonis, when removing the cable while the device is running, I get crash with stack trace very similar to second stack trace. Thanks.
