### ISSUE TITLE
[BUG] Could not reconstruct & visualize stereo depth from recording of left/right

### ISSUE THREAD

**Issue by martin0258** [luxonis/depthai#858]
**Check if issue already exists**

> 
> - Google it (e.g. *error xy* github luxonis depthai)
> - Check [troubleshooting](https://docs.luxonis.com/en/latest/pages/troubleshooting/) in documentation.

Yes, but I found nothing related

**Describe the bug**
As title, I following the usage of [replaying](https://docs.luxonis.com/projects/sdk/en/latest/features/replaying/) from docs, but I could not reconstruct & visualize stereo depth from the recording of the left/right monoframes.

Sample code from [doc](https://docs.luxonis.com/projects/sdk/en/latest/components/stereo_component/#usage)
```python
with OakCamera() as oak:
    # Create stereo component, initialize left/right MonoCamera nodes for 800P and 60FPS
    stereo = oak.create_stereo('800p', fps=60)

    # Visualize normalized and colorized disparity stream
    oak.visualize(stereo.out.depth)
    # Start the pipeline, continuously poll
    oak.start(blocking=True)
```

**Minimal Reproducible Example**
~By using the recording `18443010B1C8361300.zip` and run the following code~
**UPDATE**: The bug has been idenfitied by Luxonis's staff.
Because the file is related to our client's business, so it's no longer available to minize privacy risk.

Below is my code which results in an error
```python
from depthai_sdk import OakCamera

with OakCamera(replay='18443010B1C8361300') as oak:
    color = oak.create_camera('color')
    left = oak.create_camera('left')
    right = oak.create_camera('right')
    stereo = oak.create_stereo(left=left, right=right)
    oak.visualize([color, left, right, stereo.out.depth], scale=1/3)
    oak.start(blocking=True)
```

I got the following runtime error
```
Available streams from recording: ['color', 'right', 'left']
Closing OAK camera
Closing replay
Traceback (most recent call last):
  File "/home/martin/Projects/sock_rotation_ai_poc/replay.py", line 10, in <module>
    oak.start(blocking=True)
  File "/home/martin/Projects/sock_rotation_ai_poc/depthai/depthai_sdk/src/depthai_sdk/oak_camera.py", line 267, in start
    self.build()  # Build the pipeline
  File "/home/martin/Projects/sock_rotation_ai_poc/depthai/depthai_sdk/src/depthai_sdk/oak_camera.py", line 354, in build
    xouts = out.setup(self._pipeline, self._oak.device, names)
  File "/home/martin/Projects/sock_rotation_ai_poc/depthai/depthai_sdk/src/depthai_sdk/classes/output_config.py", line 53, in setup
    xoutbase: XoutBase = self.output(pipeline, device)
  File "/home/martin/Projects/sock_rotation_ai_poc/depthai/depthai_sdk/src/depthai_sdk/components/stereo_component.py", line 214, in depth
    mono_frames=StreamXout(self._comp.node.id, self._comp.right.out),
  File "/home/martin/Projects/sock_rotation_ai_poc/depthai/depthai_sdk/src/depthai_sdk/oak_outputs/xout_base.py", line 17, in __init__
    self.name = f"{str(id)}_{out.name}"
AttributeError: 'Out' object has no attribute 'name'
```

**Expected behavior**
It should reconstruct & visualize the depth.

**Screenshots**
NA

**Pipeline Graph**

> Please also provide a screenshot of your pipeline using the [DepthAI Pipeline Graph](https://github.com/geaxgx/depthai_pipeline_graph).

I guess the graph is not so helpful in this case? The MRE is quite simple.

**Attach system log**
```json
{
    "architecture": "64bit ELF",
    "machine": "x86_64",
    "platform": "Linux-5.15.0-56-generic-x86_64-with-glibc2.31",
    "processor": "x86_64",
    "python_build": "main Nov 22 2022 15:55:03",
    "python_compiler": "GCC 10.4.0",
    "python_implementation": "CPython",
    "python_version": "3.9.15",
    "release": "5.15.0-56-generic",
    "system": "Linux",
    "version": "#62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022",
    "win32_ver": "",
    "packages": [
        "absl-py==1.3.0",
        "aiohttp==3.8.3",
        "aiosignal==1.3.1",
        "albumentations==1.3.0",
        "anomalib==0.3.7",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.6.2",
        "argon2-cffi==21.3.0",
        "argon2-cffi-bindings==21.2.0",
        "asttokens==2.2.0",
        "async-timeout==4.0.2",
        "attrs==22.1.0",
        "Babel==2.11.0",
        "backcall==0.2.0",
        "bcrypt==4.0.1",
        "beautifulsoup4==4.11.1",
        "bleach==5.0.1",
        "blobconverter==1.3.0",
        "boto3==1.26.21",
        "botocore==1.29.21",
        "cachetools==5.2.0",
        "certifi==2022.9.24",
        "cffi==1.15.1",
        "charset-normalizer==2.1.1",
        "click==8.1.3",
        "comet-ml==3.31.19",
        "configobj==5.0.6",
        "contourpy==1.0.6",
        "cryptography==38.0.4",
        "cycler==0.11.0",
        "debugpy==1.6.4",
        "decorator==5.1.1",
        "defusedxml==0.7.1",
        "depthai==2.19.1.0",
        "depthai-sdk==1.9.0",
        "distinctipy==1.2.2",
        "docker-pycreds==0.4.0",
        "docstring-parser==0.15",
        "dulwich==0.20.50",
        "einops==0.6.0",
        "entrypoints==0.4",
        "everett==3.1.0",
        "executing==1.2.0",
        "fastapi==0.88.0",
        "fastjsonschema==2.16.2",
        "ffmpy==0.3.0",
        "fonttools==4.38.0",
        "frozenlist==1.3.3",
        "fsspec==2022.11.0",
        "gitdb==4.0.10",
        "GitPython==3.1.29",
        "google-auth==2.15.0",
        "google-auth-oauthlib==0.4.6",
        "gradio==3.12.0",
        "grpcio==1.51.1",
        "h11==0.12.0",
        "httpcore==0.15.0",
        "httpx==0.23.1",
        "idna==3.4",
        "imageio==2.22.4",
        "imgaug==0.4.0",
        "importlib-metadata==5.1.0",
        "ipykernel==6.17.1",
        "ipython==8.7.0",
        "ipython-genutils==0.2.0",
        "jedi==0.18.2",
        "Jinja2==3.1.2",
        "jmespath==1.0.1",
        "joblib==1.2.0",
        "json5==0.9.10",
        "jsonargparse==4.18.0",
        "jsonschema==4.17.3",
        "jupyter-server==1.23.3",
        "jupyter_client==7.4.7",
        "jupyter_core==5.1.0",
        "jupyterlab==3.5.0",
        "jupyterlab-pygments==0.2.2",
        "jupyterlab_server==2.16.3",
        "kiwisolver==1.4.4",
        "kornia==0.6.8",
        "linkify-it-py==1.0.3",
        "Markdown==3.4.1",
        "markdown-it-py==2.1.0",
        "MarkupSafe==2.1.1",
        "marshmallow==3.17.0",
        "matplotlib==3.6.1",
        "matplotlib-inline==0.1.6",
        "mdit-py-plugins==0.3.1",
        "mdurl==0.1.2",
        "mistune==2.0.4",
        "multidict==6.0.2",
        "nbclassic==0.4.8",
        "nbclient==0.7.2",
        "nbconvert==7.2.5",
        "nbformat==5.7.0",
        "nest-asyncio==1.5.6",
        "networkx==2.8.8",
        "notebook==6.5.2",
        "notebook_shim==0.2.2",
        "numpy==1.23.5",
        "oauthlib==3.2.2",
        "omegaconf==2.2.3",
        "opencv-contrib-python==4.6.0.66",
        "opencv-python==4.6.0.66",
        "orjson==3.8.2",
        "packaging==21.3",
        "pandas==1.5.2",
        "pandocfilters==1.5.0",
        "paramiko==2.12.0",
        "parso==0.8.3",
        "pathtools==0.1.2",
        "pexpect==4.8.0",
        "pickleshare==0.7.5",
        "Pillow==9.3.0",
        "pip==22.3.1",
        "platformdirs==2.5.4",
        "prometheus-client==0.15.0",
        "promise==2.3",
        "prompt-toolkit==3.0.33",
        "protobuf==3.20.1",
        "psutil==5.9.4",
        "ptyprocess==0.7.0",
        "pure-eval==0.2.2",
        "pyasn1==0.4.8",
        "pyasn1-modules==0.2.8",
        "pycparser==2.21",
        "pycryptodome==3.16.0",
        "pydantic==1.10.2",
        "pyDeprecate==0.3.2",
        "pydub==0.25.1",
        "Pygments==2.13.0",
        "PyNaCl==1.5.0",
        "pyparsing==3.0.9",
        "pyrsistent==0.19.2",
        "PySide2==5.15.2.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.5",
        "pytorch-lightning==1.6.5",
        "pytube==12.1.0",
        "PyTurboJPEG==1.6.4",
        "pytz==2022.6",
        "PyWavelets==1.4.1",
        "PyYAML==6.0",
        "pyzmq==24.0.1",
        "Qt.py==1.3.7",
        "qudida==0.0.4",
        "requests==2.28.1",
        "requests-oauthlib==1.3.1",
        "requests-toolbelt==0.10.1",
        "rfc3986==1.5.0",
        "rsa==4.9",
        "s3transfer==0.6.0",
        "scikit-image==0.19.3",
        "scikit-learn==1.1.3",
        "scipy==1.9.3",
        "semantic-version==2.10.0",
        "Send2Trash==1.8.0",
        "sentry-sdk==1.11.1",
        "setproctitle==1.3.2",
        "setuptools==65.5.1",
        "Shapely==1.8.5.post1",
        "shiboken2==5.15.2.1",
        "shortuuid==1.0.11",
        "simplejson==3.18.0",
        "six==1.16.0",
        "smmap==5.0.0",
        "sniffio==1.3.0",
        "soupsieve==2.3.2.post1",
        "stack-data==0.6.2",
        "starlette==0.22.0",
        "tensorboard==2.11.0",
        "tensorboard-data-server==0.6.1",
        "tensorboard-plugin-wit==1.8.1",
        "terminado==0.17.0",
        "threadpoolctl==3.1.0",
        "tifffile==2022.10.10",
        "timm==0.5.4",
        "tinycss2==1.2.1",
        "tomli==2.0.1",
        "torch==1.12.0",
        "torchmetrics==0.9.3",
        "torchtext==0.13.0",
        "torchvision==0.13.0",
        "tornado==6.2",
        "tqdm==4.64.1",
        "traitlets==5.6.0",
        "typing_extensions==4.4.0",
        "uc-micro-py==1.0.1",
        "urllib3==1.26.13",
        "uvicorn==0.20.0",
        "wandb==0.12.17",
        "wcwidth==0.2.5",
        "webencodings==0.5.1",
        "websocket-client==1.3.3",
        "websockets==10.4",
        "Werkzeug==2.2.2",
        "wheel==0.38.4",
        "wrapt==1.14.1",
        "wurlitzer==3.0.3",
        "xmltodict==0.13.0",
        "yarl==1.8.1",
        "zipp==3.11.0"
    ],
    "usb": [
        "NoLib"
    ],
    "uname": [
        "Linux SS-KINGS 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64"
    ]
}
```

**Additional context**
Forgive me if it's my incorrect API usage and not a bug.

I simply wrote the code because the docs said so. Maybe my interpretation of the docs is incorrect?
> Because [Recording](https://docs.luxonis.com/projects/sdk/en/latest/features/recording/#recording) saves calibration data and can save synchronized left+right mono streames we can achieve full depth reconstruction.

If I changed `xout_base.py` to bypass the error as a workaround, there was no error but depth was not shown -- only `color`, `left, `right` were visualized as 3 frames, respectively.

**Comment by Erol444** [comment]
Hi @martin0258 , could you post the graph as well? You can create it via `oak.show_graph()`

**Comment by martin0258** [comment]
@Erol444 
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/1118615/205439452-7f42a750-b2d7-4f65-be28-ff0594d1a3e4.png">

**Comment by daniilpastukhov** [comment]
Hi @martin0258, thanks for the issue. I've found the bug that causes tha error. When using replay, `depthai_sdk.CameraComponent` is being used instead of expected `depthai.MonoCamera` for left/right videos. I am working on a fix, I will let you now once it's fixed.
